targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
          case_from_dart_to_sql: snake_case