// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfhdZOx7dVtr1s4S_7tvN2_zQkaStZIys',
    appId: '1:1045911810633:web:6b26b17a2f5a48a0a0c598',
    messagingSenderId: '1045911810633',
    projectId: 'arqueopi-hub',
    authDomain: 'arqueopi-hub.firebaseapp.com',
    storageBucket: 'arqueopi-hub.firebasestorage.app',
    measurementId: 'G-5ZXDHWSZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6fVzahip4Qj_d0USbGlSrpIbBD3VB7E',
    appId: '1:1045911810633:android:8b90761db4fcfbe8a0c598',
    messagingSenderId: '1045911810633',
    projectId: 'arqueopi-hub',
    storageBucket: 'arqueopi-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-XAW__S6bd5n561yvRMNdVAW67IaYLnM',
    appId: '1:1045911810633:ios:75d3cb5515183c43a0c598',
    messagingSenderId: '1045911810633',
    projectId: 'arqueopi-hub',
    storageBucket: 'arqueopi-hub.firebasestorage.app',
    iosBundleId: 'com.example.sistemaColetaArqueologica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-XAW__S6bd5n561yvRMNdVAW67IaYLnM',
    appId: '1:1045911810633:ios:75d3cb5515183c43a0c598',
    messagingSenderId: '1045911810633',
    projectId: 'arqueopi-hub',
    storageBucket: 'arqueopi-hub.firebasestorage.app',
    iosBundleId: 'com.example.sistemaColetaArqueologica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfhdZOx7dVtr1s4S_7tvN2_zQkaStZIys',
    appId: '1:1045911810633:web:ffe185711ee5015da0c598',
    messagingSenderId: '1045911810633',
    projectId: 'arqueopi-hub',
    authDomain: 'arqueopi-hub.firebaseapp.com',
    storageBucket: 'arqueopi-hub.firebasestorage.app',
    measurementId: 'G-48TN7YZYPD',
  );
}
